author:
  brief: A software developer based in Sweden.

  name: Axel Karlsson
  legal_name: Axel H. Karlsson

# This is a custom directory containing compiled TypeScript
# and Sass, which is subsequentially used by Jekyll.
#
# We do this because we want control over the build process.
source: ./_intermediate

# See issue #15
include:
  - .well-known